<div class="row" ng-if="results != null">

	<!-- Participant Information -->
	<div class="row border-tb border-lightgray">
		<!-- <h4>ข้อมูลนักเรียน</h4> -->
		<div class="row small-pad">
			<div class="col-xs-4">
				<div class="row indent-left-2">
					<p class="text-left color-highlight"
					   style="font-size: 1.2em; margin-bottom: -20px; padding-left: 2px; margin-top: 5px;">
						{{results.identifier}} 
					</p>
					<p class="text-left" style="font-size: 1.7em; margin-bottom: 0px;">
						{{results.firstname}} {{results.lastname}}
					</p>
				</div>
			</div>
			<div class="col-xs-2">
				<div class="row text-center">
					<p class="text-left color-highlight"
					   style="font-size: 1.2em; margin-bottom: -20px; padding-left: 2px; margin-top: 5px;">
						ห้อง {{results.class}}/{{results.room}} 
					</p>
					<p class="text-left" style="font-size: 1.7em; margin-bottom: 0px;">
						เลขที่ {{results.number}}
					</p>
				</div>
			</div>
			<div class="col-xs-3">
				<div class="row text-center">
					<p class="text-left color-highlight"
					   style="font-size: 1.2em; margin-bottom: -20px; padding-left: 2px; margin-top: 5px;">
						ความสามารถพิเศษ
					</p>
					<p class="text-left" style="font-size: 1.7em; margin-bottom: 0px;">
						{{results.talent || 'ไม่มี'}}
					</p>
				</div>
			</div>
			<div class="col-xs-3">
				<div class="row text-center">
					<p class="text-left color-highlight"
					   style="font-size: 1.2em; margin-bottom: -20px; padding-left: 2px; margin-top: 5px;">
						ความต้องการพิเศษ
					</p>
					<p class="text-left" style="font-size: 1.7em; margin-bottom: 0px;"
						ng-if="results.disabilities.length > 1">
						พิการมากว่า 1 อย่าง
					</p>
					<p class="text-left" style="font-size: 1.7em; margin-bottom: 0px;"
						ng-if="results.disabilities.length == 1">
						{{ results.disabilities[0] }}
					</p>
					<p class="text-left" style="font-size: 1.7em; margin-bottom: 0px;"
						ng-if="results.disabilities.length == 0">
						ไม่มี
					</p>
				</div>
			</div>
		</div>
	</div>


	<!-- Participant Aspects -->
	<div class="col-xs-12 col-md-6 no-pad std-pad-left" 
		 style="border-right: 1px solid lightgray;">
		<h4 class="text-center">ข้อมูลความเสี่ยง</h4>

		<!-- TODO: READ ME!

			YOU PLANNED ON MAKING BELOW TABLE, BECOME A MORE AUTOMATICALLY
			GENERATED TEMPLATE BY MAKING ParticipantController RETURN A STRUCTURED ARRAY
			TO ANGULAR AND LET IT LOOP.

			YOU ALSO WERE THINKING ABOUT CREATING A SYSTEM WHERE
			REPORT CAN BE EASILY GENERATED BY USING UIs CONNECTING ALL PARTS OF DATA TOGETHER
			& BY ASSIGNING EACH RAW DATA WITH SOME KIND OF IDENTIFIER OR RELATION
			THAT IT CAN BE MARKED-DOWN/IDENTIFIED/RELATED TO/WITH EACH OTHER
			AND USE THOSE DATA IN FORM VARIOUS REPORTS

		 -->
		<!-- <div class="text-center col-xs-4" 
			 ng-repeat="aspect in results.aspects"
			 ng-click="tab.selectAspect(aspect)">
			
			<h1 style="font-size:4em" 
				ng-data-type="{{ aspect.name }}"
				ng-class="{'selected':tab.isSelected(aspect), 'rveryhigh' : aspect.veryHigh.length > 0, 'rhigh' : aspect.high.length, 'rnormal' : aspect.veryHigh.length == 0 && aspect.high.length == 0 > 0}">
				{{
				aspect.high.length +
				aspect.veryHigh.length
				}}
			</h1>
			
		</div> -->
		<table class="risk">
			<tr>
				<td class="text-center rnormal" 
					ng-click="tab.selectAspect(results.aspects.study)">
					
					<h1 style="font-size:4em" 
						data-type="การเรียน"
						ng-class="{'selected':tab.isSelected(results.aspects.study), 'rveryhigh' : results.aspects.study.veryHigh.length > 0, 'rhigh' : results.aspects.study.high.length > 0, 'rnormal' : results.aspects.study.veryHigh.length == 0 && results.aspects.study.high.length == 0}">
						{{
						results.aspects.study.high.length +
						results.aspects.study.veryHigh.length
						}}
					</h1>
					
				</td>
				<td class="text-center rveryhigh" 
					ng-click="tab.selectAspect(results.aspects.health)">
					
					<h1 style="font-size:4em" 
						data-type="สุขภาพ"
						ng-class="{'selected':tab.isSelected(results.aspects.health), 'rveryhigh' : results.aspects.health.veryHigh.length > 0, 'rhigh' : results.aspects.health.high.length > 0, 'rnormal' : results.aspects.health.veryHigh.length == 0 && results.aspects.health.high.length == 0}">
						{{
						results.aspects.health.high.length +
						results.aspects.health.veryHigh.length
						}}
					</h1>
					
				</td>
				<td class="text-center rveryhigh" 
					ng-click="tab.selectAspect(results.aspects.aggressiveness)">
					
					<h1 style="font-size:4em" 
						data-type="ความรุนแรง"
						ng-class="{'selected':tab.isSelected(results.aspects.aggressiveness), 'rveryhigh' : results.aspects.aggressiveness.veryHigh.length > 0, 'rhigh' : results.aspects.aggressiveness.high.length > 0, 'rnormal' : results.aspects.aggressiveness.veryHigh.length == 0 && results.aspects.aggressiveness.high.length == 0}">
						{{
						results.aspects.aggressiveness.high.length +
						results.aspects.aggressiveness.veryHigh.length
						}}
					</h1>
					
				</td>
			</tr>
			<tr>
				<td class="text-center rveryhigh" 
					ng-click="tab.selectAspect(results.aspects.economy)">
					
					<h1 style="font-size:4em" 
						data-type="เศรษฐกิจ"
						ng-class="{'selected':tab.isSelected(results.aspects.economy), 'rveryhigh' : results.aspects.economy.veryHigh.length > 0, 'rhigh' : results.aspects.economy.high.length > 0, 'rnormal' : results.aspects.economy.veryHigh.length == 0 && results.aspects.economy.high.length == 0}">
						{{
						results.aspects.economy.high.length +
						results.aspects.economy.veryHigh.length
						}}
					</h1>
					
				</td>
				<td class="text-center rhigh" 
					ng-click="tab.selectAspect(results.aspects.security)">
					
					<h1 style="font-size:4em" 
						data-type="ความปลอดภัย"
						ng-class="{'selected':tab.isSelected(results.aspects.security), 'rveryhigh' : results.aspects.security.veryHigh.length > 0, 'rhigh' : results.aspects.security.high.length > 0, 'rnormal' : results.aspects.security.veryHigh.length == 0 && results.aspects.security.high.length == 0}">
						{{
						results.aspects.security.high.length +
						results.aspects.security.veryHigh.length
						}}
					</h1>
					
				</td>
				<td class="text-center rnormal" 
					ng-click="tab.selectAspect(results.aspects.drugs)">
					
					<h1 style="font-size:4em" 
						data-type="สารเสพติด"
						ng-class="{'selected':tab.isSelected(results.aspects.drugs), 'rveryhigh' : results.aspects.drugs.veryHigh.length > 0, 'rhigh' : results.aspects.drugs.high.length > 0, 'rnormal' : results.aspects.drugs.veryHigh.length == 0 && results.aspects.drugs.high.length == 0}">
						{{
						results.aspects.drugs.high.length +
						results.aspects.drugs.veryHigh.length
						}}
					</h1>
					
				</td>
			</tr>
			<tr>
				<td class="text-center rhigh" 
					ng-click="tab.selectAspect(results.aspects.sexuality)">
					
					<h1 style="font-size:4em" 
						data-type="เพศ"
						ng-class="{'selected':tab.isSelected(results.aspects.sexuality), 'rveryhigh' : results.aspects.sexuality.veryHigh.length > 0, 'rhigh' : results.aspects.sexuality.high.length > 0, 'rnormal' : results.aspects.sexuality.veryHigh.length == 0 && results.aspects.sexuality.high.length == 0}">
						{{
						results.aspects.sexuality.high.length +
						results.aspects.sexuality.veryHigh.length
						}}
					</h1>
					
				</td>
				<td class="text-center rnormal" 
					ng-click="tab.selectAspect(results.aspects.games)">
					
					<h1 style="font-size:4em" 
						data-type="ติดเกม"
						ng-class="{'selected':tab.isSelected(results.aspects.games), 'rveryhigh' : results.aspects.games.veryHigh.length > 0, 'rhigh' : results.aspects.games.high.length > 0, 'rnormal' : results.aspects.games.veryHigh.length == 0 && results.aspects.games.high.length == 0}">
						{{
						results.aspects.games.high.length +
						results.aspects.games.veryHigh.length
						}}
					</h1>
					
				</td>
				<td class="text-center rveryhigh" 
					ng-click="tab.selectAspect(results.aspects.electronics)">
					
					<h1 style="font-size:4em" 
						data-type="เครื่องมือสื่อสาร"
						ng-class="{'selected':tab.isSelected(results.aspects.electronics), 'rveryhigh' : results.aspects.electronics.veryHigh.length > 0, 'rhigh' : results.aspects.electronics.high.length, 'rnormal' : results.aspects.electronics.veryHigh.length == 0 && results.aspects.electronics.high.length == 0 > 0}">
						{{
						results.aspects.electronics.high.length +
						results.aspects.electronics.veryHigh.length
						}}
					</h1>
					
				</td>
			</tr>
		</table>
	</div>

	<!-- Apsect Views -->
	<div class="col-xs-12 col-md-6"
		 ui-view="risk-aspect-detail">
		<div class="vertical-align text-center anim-fade"
			 ng-if="!tab.selectedAspect">
			<h4 class="color-lowlight" 
				style="margin:auto;">
				กรุณาเลือกด้าน<br/>
				เพื่อดูรายละเอียดความเสี่ยง
			</h4>
		</div>
		<div class="anim-fade"
			 ng-if="tab.selectedAspect">
			 <h4 class="text-center">รายละเอียดความเสี่ยง</h4>
			<div ng-if="tab.selectedAspect.high.length == 0 && tab.selectedAspect.veryHigh.length == 0">
				<h1 class="auto-margin text-center" style="color: green">
					ปกติ
				</h1>
			</div>
			<div ng-if="tab.selectedAspect.high.length > 0 || tab.selectedAspect.veryHigh.length > 0">
				<ul ng-if="tab.selectedAspect.high.length > 0">
					<div class="color-accent">เสี่ยง</div>
					<li ng-repeat="item in tab.selectedAspect.high">
						{{item.name}}
					</li>
				</ul>
				<ul ng-if="tab.selectedAspect.veryHigh.length > 0"> 
					<div class="color-accent">มีปัญหา</div>
					<li ng-repeat="item in tab.selectedAspect.veryHigh">
						{{item.name}}
					</li>
				</ul>
			</div>
		</div>
	</div>

</div>

<div class="col-xs-12 text-center no-border flex-container flex-center" 
	 style="height: 82.5vh" 
	 ng-if="results == null">
	<h2 class="col-xs-12 text-center">
		{{ errorMessage }}
	</h2>
</div>